import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <footer className="absolute bottom-0 text-center p-2 bg-zinc-900 text-white/50 w-full text-sm">
          <p>&copy; 2024 Marco. All rights reserved.</p>
        </footer>
      </body>
    </html>
  );
}
